---
- name: Server und Docker updaten, aufräumen und ggf. neustarten
  hosts: all
  become: yes

  tasks:
    - name: Prüfen ob docker.list.disabled existiert und ggf. aktivieren
      ansible.builtin.shell: |
        if [ -f /etc/apt/sources.list.d/docker.list.disabled ]; then
          mv /etc/apt/sources.list.d/docker.list.disabled /etc/apt/sources.list.d/docker.list
        fi
      args:
        executable: /bin/bash

    - name: Codenamen in Docker Repository auf resolute korrigieren (falls vorhanden)
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        regexp: '^deb.*download\.docker\.com'
        line: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu resolute stable'
      ignore_errors: yes

    - name: Apt-Cache aktualisieren und alle Pakete upgraden
      ansible.builtin.apt:
        update_cache: yes
        upgrade: safe
        autoremove: yes

    - name: Prüfen, ob ein Neustart erforderlich ist
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Server neu starten, falls ein Kernel-Update das erfordert
      ansible.builtin.reboot:
        msg: "Automatischer Neustart durch Ansible nach System-Update"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists
